version: '3.9'

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: pswd
      POSTGRES_DB: tupochatdb
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  chat:
    build: .
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://root:pswd@db:5432/tupochatdb
    ports:
      - "5522:5522"
    restart: unless-stopped